// DigiEDU – Zariadenia (generované z EXPORT.xlsx)
const DEVICES = [
  {
    "id": 1,
    "name": "Lenovo Tab K11 Enhanced Edition + Folio Keyboard SK/CZ + digital pen",
    "pn": "TAB ZAFS0262CZ+WAR+MDM2",
    "sn_sample": "ZAF...",
    "note": "Zlúčené: 3 varianty s preklepy (Tak/Tab, zátvorkky)",
    "description": "11\" Android tablet s procesorom MediaTek Helio G88, 4/8 GB RAM a 64/128 GB úložiskom eMMC 5.1. Displej IPS 1920×1200 px s ochranou Corning Gorilla Glass. Súčasťou balenia je foliová klávesnica SK/CZ a stylus Tab Pen Plus s 4096 úrovňami citlivosti. Batéria 7 040 mAh, Wi-Fi 5, Bluetooth 5.1, USB-C. Certifikovaný pre Android Enterprise (MDM).",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/lenovotabk11enhancededition/01-lenovo-tab-k11-enhanced-edition-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/Lenovo_Tablets/Tab_K11_Enhanced_Edition/Tab_K11_Enhanced_Edition_Spec.PDF",
    "official_page": "https://psref.lenovo.com/Product/Tab_K11_Enhanced_Edition",
    "manufacturer": "Lenovo"
  },
  {
    "id": 2,
    "name": "Lenovo Idea Tab Pro (TB373FU) + Lenovo Keyboard Pack + Lenovo Tab Pen Plus",
    "pn": "ZAE50188CZ",
    "sn_sample": "ZAE...",
    "note": "",
    "description": "12,7\" tablet s procesorom MediaTek Dimensity 8300 Octa-core, 8 GB LPDDR5 RAM a 128/256 GB úložiskom. Displej IPS 3K (2944×1840) s obnovovacou frekvenciou 144 Hz a Gorilla Glass 3. Súčasťou je foliová klávesnica a stylus Tab Pen Plus. Batéria 10 200 mAh s rýchlym nabíjaním 45 W. Certifikácia IP52, Android 14.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/lenovoideataborpro/01-lenovo-idea-tab-pro-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/Lenovo_Tablets/Idea_Tab_Pro/Idea_Tab_Pro_Spec.pdf",
    "official_page": "https://psref.lenovo.com/Product/LenovoTablets/Idea_Tab_Pro",
    "manufacturer": "Lenovo"
  },
  {
    "id": 3,
    "name": "Samsung Galaxy Tab S9 + pen + keyboard + adapter + MDM",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "11\" prémiový Android tablet s čipom Snapdragon 8 Gen 2, 8/12 GB RAM a 128/256 GB úložiskom. Dynamic AMOLED 2X displej (2560×1600 px) s obnovovacou frekvenciou 120 Hz. Vybavený S Pen perom s latenciou 2,8 ms, certifikáciou IP68, Wi-Fi 6E a Bluetooth 5.3. Batéria 8 400 mAh, USB 3.2 Gen 1 Type-C.",
    "photo_device": "https://images.samsung.com/is/image/samsung/p6pim/global/sm-x710nzaaxfe/gallery/global-galaxy-tab-s9-wifi-sm-x710-sm-x710nzaaxfe-537551067?$730_730_PNG$",
    "photo_label": "https://www.samsung.com/global/galaxy/galaxy-tab-s9/",
    "official_page": "https://www.samsung.com/global/galaxy/galaxy-tab-s9/",
    "manufacturer": "Samsung"
  },
  {
    "id": 4,
    "name": "Lenovo IdeaPad Duet 3 11IAN8",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "2-v-1 chromebook/tablet s 11\" IPS FHD (1920×1200) displejom a procesorom Intel Pentium N6000. 4 GB RAM (LPDDR4X), 128 GB eMMC. Klávesnica Folio je súčasťou balenia, dotykový displej, stylus USI Pen (voliteľný). Batéria 7 040 mAh, Wi-Fi 6, USB-C, Chrome OS. Hmotnosť iba 920 g.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/lenovo-ideapad-duet-3-chromebook/01-lenovo-ideapad-duet-3-chromebook-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/IdeaPad/IdeaPad_Duet_3_Chromebook_11_IAN8/IdeaPad_Duet_3_Chromebook_11_IAN8_Spec.pdf",
    "official_page": "https://psref.lenovo.com/Product/IdeaPad/IdeaPad_Duet_3_Chromebook_11_IAN8",
    "manufacturer": "Lenovo"
  },
  {
    "id": 5,
    "name": "Lenovo ThinkBook 14 G7 ARP",
    "pn": "21MVS02000",
    "sn_sample": "MP...",
    "note": "",
    "description": "14\" biznis notebook s procesorom AMD Ryzen 5/7 7000 Series, až 64 GB DDR5-4800 RAM a SSD NVMe PCIe 4.0 až 2 TB. Displej WUXGA IPS 1920×1200, 300 nit, anti-glare. Hliníkové šasi s certifikáciou MIL-STD-810H, čítačka odtlačkov prstov, TPM 2.0, Wi-Fi 6, Bluetooth 5.3, HDMI 2.1. Batéria 45 Wh, hmotnosť od 1,38 kg.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/thinkbook14g7arp/01-thinkbook-14-g7-arp-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkBook/ThinkBook_14_G7_ARP/ThinkBook_14_G7_ARP_Spec.pdf",
    "official_page": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_14_G7_ARP",
    "manufacturer": "Lenovo"
  },
  {
    "id": 6,
    "name": "Lenovo ThinkBook 14 2-in-1 G4 IML",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "14\" konvertibilný 2-v-1 notebook s procesorom Intel Core Ultra 5/7 (Meteor Lake), až 32 GB LPDDR5X RAM a SSD NVMe PCIe 4.0. Dotykový displej WUXGA IPS s Active Pen 2. Dizajn 360° závesov, hliníkové šasi s certifikáciou MIL-STD-810H, Wi-Fi 6E, Bluetooth 5.3. Windows 11 Pro, batéria 84 Wh.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/thinkbook142in1g4iml/01-thinkbook-14-2-in-1-g4-iml-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkBook/ThinkBook_14_2-in-1_G4_IML/ThinkBook_14_2-in-1_G4_IML_Spec.pdf",
    "official_page": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_14_2-in-1_G4_IML",
    "manufacturer": "Lenovo"
  },
  {
    "id": 7,
    "name": "Lenovo ThinkBook 16 G7 ARP",
    "pn": "21MWS03400",
    "sn_sample": "MP...",
    "note": "",
    "description": "16\" biznis notebook s procesorom AMD Ryzen 5/7 7000 Series, až 64 GB DDR5-4800 RAM a SSD NVMe PCIe 4.0 až 2 TB. Displej WUXGA IPS 1920×1200, 300 nit, anti-glare. Certifikácia MIL-STD-810H, čítačka odtlačkov, TPM 2.0, Wi-Fi 6, Bluetooth 5.3, HDMI 2.1, USB4/Thunderbolt 4. Batéria 45 Wh.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/thinkbook16g7arp/01-thinkbook-16-g7-arp-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkBook/ThinkBook_16_G7_ARP/ThinkBook_16_G7_ARP_Spec.pdf",
    "official_page": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_16_G7_ARP",
    "manufacturer": "Lenovo"
  },
  {
    "id": 8,
    "name": "Lenovo ThinkBook 16 G7 ARP TOUCH",
    "pn": "21MWS03300",
    "sn_sample": "MP...",
    "note": "",
    "description": "16\" dotykový 2-v-1 biznis notebook (rovnaká platforma ako G7 ARP) s AMD Ryzen 7000, IPS WUXGA dotykovým displejom (1920×1200). Plná kompatibilita so stylusom, certifikácia MIL-STD-810H. Konektivita: Wi-Fi 6, BT 5.3, USB4, HDMI 2.1. Windows 11 Pro.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/thinkbook16g7arp/01-thinkbook-16-g7-arp-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkBook/ThinkBook_16_G7_ARP/ThinkBook_16_G7_ARP_Spec.pdf",
    "official_page": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_16_G7_ARP",
    "manufacturer": "Lenovo"
  },
  {
    "id": 9,
    "name": "Acer TravelMate P2 TMP214-56-TCO-31SS",
    "pn": "—",
    "sn_sample": "NX...",
    "note": "",
    "description": "14\" biznis notebook s procesorom Intel Core i3/i5/i7 13. generácie (Raptor Lake-U), až 32 GB DDR4 RAM a SSD PCIe NVMe. Displej IPS FHD (1920×1080), anti-glare, 300 nit. Certifikácia MIL-STD 810H, TPM 2.0, čítačka odtlačkov, Wi-Fi 6E, Bluetooth 5.3. Splňuje štandard TCO Certified a EPEAT Silver.",
    "photo_device": "https://static.acer.com/up/Resource/Acer/Laptops/TravelMate_P2/Images/20230808/1b73a576-6a55-41ef-83a0-a6fd3b574ec7.png",
    "photo_label": "https://www.acer.com/eu-en/laptops/travelmate/travelmate-p2/pdp/NX.B1DEG.00G",
    "official_page": "https://www.acer.com/eu-en/laptops/travelmate/travelmate-p2",
    "manufacturer": "Acer"
  },
  {
    "id": 10,
    "name": "ASUS B3604CMA-Q90503XA + SBOX HS-707 slúchadlá s mikrofónom USB",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "16\" biznis notebook s procesorom Intel Core Ultra 5 Processor 125H (Meteor Lake), 16 GB LPDDR5 RAM a 512 GB SSD NVMe. Displej FHD IPS 1920×1080, 300 nit, anti-glare. Šasi s MIL-STD-810H certifikáciou, biometrické zabezpečenie (odtlačok + IR kamera), Wi-Fi 6E, Bluetooth 5.3. Windows 11 Pro.",
    "photo_device": "https://dlcdnets.asus.com/pub/ASUS/nb/ExpertBook_B3/B3604CMA/B3604CMA_overview.jpg",
    "photo_label": "https://www.asus.com/laptops/for-work/expertbook/asus-expertbook-b3-flip-b3604cma/helpdesk_manual/",
    "official_page": "https://www.asus.com/laptops/for-work/expertbook/asus-expertbook-b3-flip-b3604cma/",
    "manufacturer": "ASUS"
  },
  {
    "id": 11,
    "name": "OptiPlex Tower (7020) + Dell 24 Video Conferencing Monitor P2424HEB + GEMBIRD FD2-SD-1 + SBOX HS-707",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Stolový počítač Dell OptiPlex Tower 7020 s procesorom Intel Core i3/i5/i7 14. generácie, DDR5 RAM (až 64 GB) a SSD NVMe PCIe. Komplet obsahuje 24\" monitor Dell P2424HEB s integrovanou webkamerou, čítačku kariet GEMBIRD a USB headset SBOX HS-707. Wi-Fi 6E, 10 USB portov vrátane USB-C, Windows 11 Pro.",
    "photo_device": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/desktops/optiplex/optiplex-tower-7020/media-gallery/desktop-optiplex-7020t-nt-blue-gallery-4.psd?fmt=png,rgb&wid=570&hei=455",
    "photo_label": "https://www.dell.com/support/manuals/en-us/optiplex-7020-tower-desktop",
    "official_page": "https://www.dell.com/en-us/shop/desktop-computers/optiplex-tower/spd/optiplex-7020t-desktop",
    "manufacturer": "OptiPlex"
  },
  {
    "id": 12,
    "name": "Dell OptiPlex All-in-One Plus 7420 + SBOX HS-707 slúchadlá s mikrofónom USB",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "23,8\" All-in-One počítač s procesorom Intel Core i5/i7 14. generácie, DDR5 RAM (až 64 GB), SSD NVMe PCIe 4.0. Displej FHD IPS s dotykovým ovládaním (voliteľné), integrovaná kamera Full HD. Wi-Fi 6E, Bluetooth 5.3, USB 3.2 Gen 2, Thunderbolt 4, HDMI. Windows 11 Pro. Ergonomický stojan s nastavením výšky.",
    "photo_device": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/desktops/optiplex/optiplex-aio/7420/media-gallery/optiplex-aio-7420-nt-blue-gallery-1.psd?fmt=png,rgb&wid=570&hei=455",
    "photo_label": "https://www.dell.com/support/manuals/en-us/optiplex-aio-7420-desktop",
    "official_page": "https://www.dell.com/en-us/shop/desktop-computers/optiplex-all-in-one-plus-7420/spd/optiplex-all-in-one-plus-7420-desktop",
    "manufacturer": "Dell"
  },
  {
    "id": 13,
    "name": "Lenovo ThinkCentre M90t gen 6 + Lenovo ThinkVision T24v-30 + Sbox HS-707",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Komplet stolového počítača Lenovo ThinkCentre M90t Gen 6 (Intel Core i5/i7 14. gen., DDR5, SSD PCIe) s 24\" monitorom ThinkVision T24v-30 (FHD IPS, webkamera, reproduktory) a USB headsetom SBOX HS-707. Certifikácia Intel vPro, TPM 2.0, Wi-Fi 6E, Bluetooth 5.3. Windows 11 Pro.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/thinkcentrem90t/01-thinkcentre-m90t-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkCentre/ThinkCentre_M90t_Gen_5/ThinkCentre_M90t_Gen_5_Spec.pdf",
    "official_page": "https://www.lenovo.com/us/en/c/desktops/thinkcentre/m-series-towers/",
    "manufacturer": "Lenovo"
  },
  {
    "id": 14,
    "name": "HP ProStudio 4 All-in-One G1i + Sbox HS-707 slúchadlá s mikrofónom USB",
    "pn": "B6HL6ES",
    "sn_sample": "—",
    "note": "",
    "description": "23,8\" kreatívna pracovná stanica All-in-One s procesorom Intel Core Ultra (Meteor Lake), NVIDIA RTX grafika (voliteľná), až 64 GB DDR5 RAM a SSD NVMe PCIe 4.0. Displej QHD IPS s farebnou presnosťou DCI-P3, integrovaná 5MP IR webkamera, repro 9W, Wi-Fi 6E, Thunderbolt 4. Windows 11 Pro.",
    "photo_device": "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08618154.png",
    "photo_label": "https://support.hp.com/us-en/product/details/hp-prostudio-4-all-in-one-g1i/details",
    "official_page": "https://www.hp.com/us-en/desktops/pro-studio-all-in-one.html",
    "manufacturer": "HP"
  },
  {
    "id": 15,
    "name": "Monitor Lenovo ThinkVision T24v-30",
    "pn": "63D8MAR3EU",
    "sn_sample": "—",
    "note": "",
    "description": "23,8\" profesionálny monitor FHD (1920×1080) s IPS panelom, 99 % sRGB a 250 nit. Integrovaná 2 MP IR+RGB webkamera (Windows Hello), 2× reproduktory 3W a 2× mikrofóny s redukciou hluku. Konektivita: HDMI 1.4, DisplayPort 1.2, VGA, 4× USB. Ergonomický stojan (výška, náklon, rotácia, pivot). Certifikácie EPEAT Gold, TCO 9.0, TÜV Flicker Free.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/thinkvisiont24v-30/01-thinkvision-t24v-30-hero.jpg",
    "photo_label": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkVision/ThinkVision_T24v-30/ThinkVision_T24v-30_Spec.pdf",
    "official_page": "https://www.lenovo.com/us/en/p/accessories-and-software/monitors/office/63d8mar3us",
    "manufacturer": "Monitor"
  },
  {
    "id": 16,
    "name": "Monitor ViewSonic VG2409U-2",
    "pn": "VG2409U-2",
    "sn_sample": "—",
    "note": "",
    "description": "23,8\" ergonomický monitor FHD (1920×1080) s IPS panelom, 60 Hz a časom odozvy 5 ms. Pokrytie 100 % sRGB, jas 250 cd/m². Vstupné rozhrania: HDMI, DisplayPort, 4× USB-A, 1× USB-C 65 W PD. Nastaviteľný stojan (výška, náklon, rotácia, pivot), VESA 100 × 100 mm. Certifikácia ENERGY STAR a TCO.",
    "photo_device": "https://www.viewsonic.com/dam/news/press/2022/4k-monitors/VG2409U_hero.jpg",
    "photo_label": "https://www.viewsonic.com/global/products/lcd/VG2409U-2",
    "official_page": "https://www.viewsonic.com/global/products/lcd/VG2409U-2",
    "manufacturer": "Monitor"
  },
  {
    "id": 17,
    "name": "ViewSonic VG2456",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "23,8\" ergonomický kancelársky monitor FHD (1920×1080) s IPS panelom, obnovovacou frekvenciou 75 Hz a dobou odozvy 5 ms (GtG). Jas 250 cd/m², 100 % sRGB. Vstupné rozhrania: HDMI 1.4, DisplayPort 1.2, VGA, 4× USB-A Hub (USB 3.2 Gen 1), 1× USB-C 90 W PD. Nastaviteľný stojan, VESA 100 × 100 mm. Certifikácia TCO.",
    "photo_device": "https://www.viewsonic.com/dam/products/VG2456/VG2456_hero.jpg",
    "photo_label": "https://www.viewsonic.com/global/products/lcd/VG2456",
    "official_page": "https://www.viewsonic.com/global/products/lcd/VG2456",
    "manufacturer": "ViewSonic"
  },
  {
    "id": 18,
    "name": "BenQ 65\" Board Pro RP6504",
    "pn": "9H.F97TC.DE3",
    "sn_sample": "—",
    "note": "Zlúčené: variant s 'RP04 Series' v názve",
    "description": "65\" interaktívny 4K UHD (3840×2160) IPS displej pre vzdelávanie, EDLA certifikovaný s Google Mobile Services. Android 13/15, 8-jadrový ARM Cortex čip, 8 GB RAM, 64 GB. Dotyk Ultra Precision IR s 50 bodmi súčasne. Reproduktory 2×20 W + 16 W subwoofer, 8-mikrofónové pole. Konektivita: 4× HDMI, DisplayPort, VGA, 2× USB-C 100 W, Wi-Fi. Ochrana Eyesafe® Certified 2.0.",
    "photo_device": "https://image01.benq.com/product/large/rp6504.jpg",
    "photo_label": "https://www.benq.com/en-us/education/user-manual/benq-board-interactive-displays/rp04-pro-series-board/product-overview.html",
    "official_page": "https://www.benq.com/en-us/education/benq-board-interactive-displays/rp04-pro-series-board.html",
    "manufacturer": "BenQ"
  },
  {
    "id": 19,
    "name": "Benq LW600ST+",
    "pn": "9H.JS377.1NE",
    "sn_sample": "—",
    "note": "",
    "description": "Krátky projektor s rozlíšením WXGA (1280×800), svietivosťou 2 600 ANSI lúmenov a pomerom hodu 0,72:1. Obraz 100\" zobrazí zo vzdialenosti 1,2 m. Kontrast 20 000:1, reproduktor 10 W. Vstupy: 2× HDMI, VGA, USB. Bezlampová technológia nie je – používa tradičnú lampu DLP. Vhodný pre učebne a konferenčné miestnosti.",
    "photo_device": "https://image01.benq.com/product/projector/lw600st-plus.jpg",
    "photo_label": "https://www.benq.com/en-us/projector/business/lw600st-plus/",
    "official_page": "https://www.benq.com/en-us/projector/business/lw600st-plus/",
    "manufacturer": "Benq"
  },
  {
    "id": 20,
    "name": "ViewSonic LS560W",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Krátky LED projektor WXGA (1280×800), svietivosť 3 000 ANSI lúmenov (stred 3 500 lúmenov), kontrast 3 000 000:1. Pomer hodu 0,49 – obraz 100\" zo vzdialenosti 1,1 m. LED zdroj s životnosťou 30 000 hodín (bez lampy, bez ortuti). Keystone H/V, 4-rohová korekcia, 360° projekcia, LAN riadenie (Crestron, AMX, PJ Link). Vstup: 2× HDMI, USB.",
    "photo_device": "https://www.viewsonic.com/dam/products/LS560W/LS560W_hero.jpg",
    "photo_label": "https://www.viewsonic.com/global/products/projectors/LS560W",
    "official_page": "https://www.viewsonic.com/global/products/projectors/LS560W",
    "manufacturer": "ViewSonic"
  },
  {
    "id": 21,
    "name": "HP Color LaserJet Pro MFP 4302dw",
    "pn": "4RA83F#B19",
    "sn_sample": "VNB...",
    "note": "",
    "description": "Farebná laserová multifunkcia A4 pre tlač, kopírovanie a skenovanie. Rýchlosť až 33 str./min (mono aj farba), rozlíšenie 600×600 dpi (HP ImageREt 2400), ADF 50 listov. Dotykový 4,3\" farebný displej, Wi-Fi dual-band 802.11ac, Wi-Fi Direct, USB 2.0, Gigabit Ethernet. Mesačná kapacita až 50 000 strán. Bezpečnosť HP Wolf Pro, ENERGY STAR.",
    "photo_device": "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08085754.png",
    "photo_label": "https://support.hp.com/us-en/product/setup-user-guides/hp-color-laserjet-pro-mfp-4301-4303dw-fdn-fdw-printer-series/model/38348029",
    "official_page": "https://www.hp.com/us-en/shop/pdp/hp-color-laserjet-pro-mfp-4302dw",
    "manufacturer": "HP"
  },
  {
    "id": 22,
    "name": "OKI MC883dn + podávač + podstavec",
    "pn": "9006108",
    "sn_sample": "—",
    "note": "",
    "description": "Farebná A3/A4 laserová multifunkcia (tlač, kopírovanie, skenovanie, fax) s LED technológiou. Rýchlosť: 35 str./min A4, 20 str./min A3. Rozlíšenie 1 200×1 200 dpi, automatický podávač dokumentov 100 listov, dotykový 7\" displej. RAM 1,26 GB, HDD 250 GB, USB + Ethernet. Certifikácia TCO. Mesačná kapacita do 100 000 strán. Záruka 3 roky on-site.",
    "photo_device": "https://www.oki.com/media/images/products/MC883dn_right_side.jpg",
    "photo_label": "https://www.oki.com/me/printing/products/colour-multifunction/mc883/specifications/",
    "official_page": "https://www.oki.com/me/printing/products/colour-multifunction/mc883/",
    "manufacturer": "OKI"
  },
  {
    "id": 23,
    "name": "OKI MC883dn + podávač + wifi modul",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Identická základná jednotka ako OKI MC883dn (35 str./min, A3 LED MFP, 1 200 dpi, 1,26 GB RAM), rozšírená o Wi-Fi modul pre bezdrôtové pripojenie a automatický podávač. Vhodná pre väčšie pracovné skupiny s vysokou mesačnou záťažou. Fax, AirPrint, Google Cloud Print. Záruka 3 roky on-site po registrácii.",
    "photo_device": "https://www.oki.com/media/images/products/MC883dn_right_side.jpg",
    "photo_label": "https://www.oki.com/me/printing/products/colour-multifunction/mc883/specifications/",
    "official_page": "https://www.oki.com/me/printing/products/colour-multifunction/mc883/",
    "manufacturer": "OKI"
  },
  {
    "id": 24,
    "name": "Naotic Naocase M500 (mobilná dokovácia stanica pre tablety)",
    "pn": "—",
    "sn_sample": "—",
    "note": "Zlúčené: Variant 1 a 3 (M500 smarty = rovnaký produkt)",
    "description": "Robustný transportný kufor (polypropylén, 670×510×372 mm, 10 kg) pre bezpečné skladovanie, transport a nabíjanie až 16 tabletov alebo 10 notebookov. Výsuvný trolley, 3 úchopové rukoväte, integrované kolesá. Inteligentné nabíjanie Smartypower (časovač, LED indikátory stavu). WiFi hotspot slot, RJ45, ochrana pred prepätím. Výroba Francúzsko, certifikácia EN 62368-1.",
    "photo_device": "https://www.naotic.fr/media/cache/news_large/uploads/newsitem/naotic-naocase-m500.jpg",
    "photo_label": "https://web.defilangues.be/wp-content/uploads/2019/04/M500.pdf",
    "official_page": "https://www.naotic.fr/en/bagage-connecte-classe-mobile",
    "manufacturer": "Naotic"
  },
  {
    "id": 25,
    "name": "Naotic Naocase M500 – Variant 2",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Alternatívna konfigurácia kufra Naocase M500 (rovnaká platforma) určená pre odlišný počet zariadení alebo typ modulárnej peny. Polypropylénové šasi 670×510×372 mm, retraktilný trolley, LED indikátory nabíjania, ochrana pred prepätím a skratom. Nabíjanie USB-C/USB-A podľa konfigurácie. Vhodné pre školské prostredie.",
    "photo_device": "https://www.naotic.fr/media/cache/news_large/uploads/newsitem/naotic-naocase-m500.jpg",
    "photo_label": "https://web.defilangues.be/wp-content/uploads/2019/04/M500.pdf",
    "official_page": "https://www.naotic.fr/en/bagage-connecte-classe-mobile",
    "manufacturer": "Naotic"
  },
  {
    "id": 26,
    "name": "Medarca nabíjací box plechový",
    "pn": "—",
    "sn_sample": "—",
    "note": "Zlúčené: 'Mercada nabíjací box' = preklep výrobcu",
    "description": "Plechový nabíjací box určený pre hromadné nabíjanie tabletov a mobilných zariadení v školách. Uzamykateľná skriňa z kovovej ocele s priehradkami pre jednotlivé zariadenia a organizovanými káblovými vývodmi. Vhodný pre pevnú montáž alebo stacionárne umiestnenie v triede. Slovenský/regionálny produkt.",
    "photo_device": "https://www.medarca.sk/images/nabijaci-box.jpg",
    "photo_label": "https://www.medarca.sk/",
    "official_page": "https://www.medarca.sk/",
    "manufacturer": "Medarca"
  },
  {
    "id": 27,
    "name": "Slúchadlá SBOX HS-707 s mikrofónom USB",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Drôtový USB 2.0 headset s nastaviteľným mikrofónom pre kancelárske a vzdelávacie použitie. Frekvenčný rozsah 20 Hz – 20 kHz, impedancia reproduktorov 32 Ω, membrána 40 mm. Citlivosť 60 dB (±3 dB), citlivosť mikrofónu 56 dB (±2 dB). Kábel PVC 1,8 m, ovládač hlasitosti a tlačidlo vypnutia mikrofónu. Plug & Play.",
    "photo_device": "https://sbox.biz/storage/gallery/headphones/HS-707-USB.jpg",
    "photo_label": "https://sbox.biz/93d8580c-2152-4ed0-b0de-2459ada02c64/headset-microphone-sbox-hs-707",
    "official_page": "https://sbox.biz/en/artikl/6871",
    "manufacturer": "Slúchadlá"
  },
  {
    "id": 28,
    "name": "TREVI AVX 565 BT + držiak",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Prenosný Bluetooth reproduktor s výkonom 2×3 W (stereo), frekvenčným rozsahom 100 Hz – 20 kHz a Bluetooth 5.0. Vstavaná lítium-iónová batéria, USB nabíjanie. Kompatibilný s AUX vstupom, podpora handsfree volaní. Dodávaný s držiakom pre montáž v triede. Vhodný pre prezentácie a multimediálne vzdelávanie.",
    "photo_device": "https://www.trevi.it/media/catalog/product/a/v/avx565bt.jpg",
    "photo_label": "https://www.trevi.it/en/avx-565-bt.html",
    "official_page": "https://www.trevi.it/en/avx-565-bt.html",
    "manufacturer": "TREVI"
  },
  {
    "id": 29,
    "name": "SVEN SPS-725",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "2.1 reproduktorový systém s celkovým výkonom 40 W (satelity 2×10 W + subwoofer 20 W). Frekvenčný rozsah 40 Hz – 20 kHz, drôtové ovládanie hlasitosti a basy. Vstupy: 3,5 mm AUX. Drevené šasi subwoofera pre lepšiu basovú reprodukciu. Vhodný pre multimediálne triedy a prezentácie.",
    "photo_device": "https://www.sven.fi/upload/product/SPS-725/SPS-725.jpg",
    "photo_label": "https://www.sven.fi/en/catalog/computer-acoustics/sps-725/",
    "official_page": "https://www.sven.fi/en/catalog/computer-acoustics/sps-725/",
    "manufacturer": "SVEN"
  },
  {
    "id": 30,
    "name": "Lenovo myš",
    "pn": "4Y50R20863",
    "sn_sample": "—",
    "note": "",
    "description": "Kompaktná drôtová USB optická myš Lenovo s rozlíšením 1 000 DPI, 3 tlačidlami (ľavé, pravé, scroll koliesko). Plug & Play, kábel 1,5 m, ergonomický tvar pre pravákov aj ľavákov. Kompatibilná s Windows, macOS a Linux. Hmotnosť cca 65 g.",
    "photo_device": "https://p1-ofp.static.pub.lenovo.com/fes/cdn/cms/gallery/lenovomouse/01-lenovo-mouse.jpg",
    "photo_label": "https://psref.lenovo.com/Product/Mouse/Mouse",
    "official_page": "https://www.lenovo.com/us/en/p/accessories-and-software/mice-and-keyboards/mice/4y50r20863",
    "manufacturer": "Lenovo"
  },
  {
    "id": 31,
    "name": "AVELI XRT-0016 (projekčná plocha – biela tabuľa)",
    "pn": "—",
    "sn_sample": "—",
    "note": "Zlúčené: XRT-00167 = preklep",
    "description": "Stojanová projekčná tabuľa na kolieskach s bielou magnetickou povrchovou úpravou. Rolovateľná alebo pevná konštrukcia vhodná pre premietanie z projektora aj písanie fixkami. Výška nastaviteľná, robustný hliníkový rám. Vhodná pre triedy a konferenčné miestnosti.",
    "photo_device": "https://www.aveli.eu/media/product/xrt-0016.jpg",
    "photo_label": "https://www.aveli.eu/product/xrt-0016/",
    "official_page": "https://www.aveli.eu/product/xrt-0016/",
    "manufacturer": "AVELI"
  },
  {
    "id": 32,
    "name": "Redukcia ku projektoru GEMBIRD A-HDMI-VGA-001",
    "pn": "—",
    "sn_sample": "—",
    "note": "",
    "description": "Pasívna redukcia HDMI (vstup) na VGA (výstup) s priemerom jacku 3,5 mm pre prenos zvuku. Prenosová rýchlosť Full HD 1080p. Kompatibilná s projektormi, monitormi a displejmi s VGA vstupom. Plug & Play, bez externého napájania. Výrobca Gembird, zástrčka HDMI typ A samec – VGA D-sub 15-pin samica.",
    "photo_device": "https://gembird.com/images/products/in_gallery/A-HDMI-VGA-001.jpg",
    "photo_label": "https://gembird.com/item.aspx?id=9002",
    "official_page": "https://gembird.com/item.aspx?id=9002",
    "manufacturer": "Redukcia"
  }
];
